package com.learnpulse.backend.ai;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.learnpulse.backend.dto.FlashcardRequest;
import com.learnpulse.backend.dto.FlashcardResponse;
import com.learnpulse.backend.entity.Role;
import com.learnpulse.backend.entity.User;
import com.learnpulse.backend.exception.ApiException;
import com.learnpulse.backend.service.FlashcardGenerationService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.ai.chat.ChatClient;
import org.springframework.ai.chat.ChatResponse;
import org.springframework.ai.chat.Generation;
import org.springframework.ai.chat.messages.AssistantMessage;
import org.springframework.ai.chat.prompt.Prompt;

import java.util.List;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
class FlashcardGenerationTest {

    @Mock
    private ChatClient chatClient;

    private PromptManager promptManager;
    private StructuredAiOutputParser structuredParser;
    private FlashcardGenerationService flashcardService;
    private User testStudent;

    @BeforeEach
    void setUp() {
        promptManager = new PromptManager();
        structuredParser = new StructuredAiOutputParser(new ObjectMapper());
        flashcardService = new FlashcardGenerationService(chatClient, promptManager, structuredParser);

        testStudent = User.builder()
                .id(UUID.randomUUID())
                .email("student@learnpulse.ai")
                .role(Role.STUDENT)
                .build();
    }

    @Test
    @DisplayName("Should successfully generate flashcards from educational material")
    void testGenerateFlashcardsSuccess() {
        FlashcardRequest request = FlashcardRequest.builder()
                .content("Inheritance is an OOP mechanism where a child class inherits properties from a superclass. Polymorphism allows methods to take many forms.")
                .cardCount(2)
                .build();

        String mockAiJson = """
                {
                  "flashcards": [
                    {"question": "What is inheritance?", "answer": "A mechanism where a child class inherits from a superclass."},
                    {"question": "What is polymorphism?", "answer": "The ability of methods to take many forms."}
                  ]
                }
                """;

        ChatResponse mockResponse = new ChatResponse(List.of(new Generation(mockAiJson)));
        when(chatClient.call(any(Prompt.class))).thenReturn(mockResponse);

        FlashcardResponse response = flashcardService.generateFlashcards(testStudent, request);
        assertNotNull(response);
        assertEquals(2, response.getFlashcards().size());
        assertEquals("What is inheritance?", response.getFlashcards().get(0).getQuestion());
    }

    @Test
    @DisplayName("Should deterministically deduplicate duplicate questions generated by AI")
    void testDeduplicateDuplicateFlashcardQuestions() {
        FlashcardRequest request = FlashcardRequest.builder()
                .content("Sample study material content.")
                .cardCount(3)
                .build();

        // AI returns 3 flashcards where question 1 & 2 are identical (case-insensitive)
        String mockDuplicateJson = """
                {
                  "flashcards": [
                    {"question": "What is JVM?", "answer": "Java Virtual Machine."},
                    {"question": "what is jvm?", "answer": "Java Virtual Machine execution engine."},
                    {"question": "What is JRE?", "answer": "Java Runtime Environment."}
                  ]
                }
                """;

        ChatResponse mockResponse = new ChatResponse(List.of(new Generation(mockDuplicateJson)));
        when(chatClient.call(any(Prompt.class))).thenReturn(mockResponse);

        FlashcardResponse response = flashcardService.generateFlashcards(testStudent, request);
        assertNotNull(response);
        // Verify duplicate 'what is jvm?' was removed, leaving 2 unique questions
        assertEquals(2, response.getFlashcards().size());
        assertEquals("What is JVM?", response.getFlashcards().get(0).getQuestion());
        assertEquals("What is JRE?", response.getFlashcards().get(1).getQuestion());
    }

    @Test
    @DisplayName("Should throw ApiException for blank or empty educational content")
    void testEmptyContentThrowsApiException() {
        FlashcardRequest request = FlashcardRequest.builder().content("  ").build();
        assertThrows(ApiException.class, () -> flashcardService.generateFlashcards(testStudent, request));
    }

    @Test
    @DisplayName("Should throw ApiException for content exceeding 15,000 chars")
    void testOversizedContentThrowsApiException() {
        String oversized = "f".repeat(15001);
        FlashcardRequest request = FlashcardRequest.builder().content(oversized).build();
        assertThrows(ApiException.class, () -> flashcardService.generateFlashcards(testStudent, request));
    }

    @Test
    @DisplayName("Should throw ApiException with HTTP 503 when ChatClient/Ollama service throws Exception")
    void testFlashcardsLlmFailureThrows503ServiceUnavailable() {
        FlashcardRequest request = FlashcardRequest.builder().content("Valid study content").cardCount(2).build();
        when(chatClient.call(any(Prompt.class))).thenThrow(new RuntimeException("Ollama connection refused"));

        ApiException exception = assertThrows(ApiException.class, () -> flashcardService.generateFlashcards(testStudent, request));
        assertEquals(org.springframework.http.HttpStatus.SERVICE_UNAVAILABLE, exception.getStatus());
        assertTrue(exception.getMessage().contains("offline or unreachable"));
    }
}
